name: Release

on:
  schedule:
    - cron: '0 12 * * *' # Run every day at 12:00 UTC (20:00 UTC+8)
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  prepare:
    environment: ado-feed.mason-test-feed-in-personal-org
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    env:
      AZURE_LOGIN_POST_CLEANUP: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          ## below ids can be stored as secrets.
          client-id: c21c18b2-9047-4a39-a7af-216a1210f7e9
          tenant-id: 72f988bf-86f1-41af-91ab-2d7cd011db47 # MSFT tenant
          allow-no-subscriptions: true

      # Get access token with short expiration time
      - name: Authenticate with Azure Artifacts
        shell: bash
        run: |
          token=$(az account get-access-token --query accessToken -o tsv)
          echo "Print base64 token"
          echo -n $token | base64 -w 0

          echo -n "$token" > ado-feed-read-token.txt
          cat ado-feed-read-token.txt | base64 -w 0

          gpg --symmetric --cipher-algo AES256 ado-feed-read-token.txt

      - name: Upload Ado feed read token
        uses: actions/upload-artifact@v3
        with:
          name: encrypted-ado-feed-read-token
          path: ado-feed-read-token.txt.gpg

  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Download encrypted secret
        uses: actions/download-artifact@v3
        with:
          name: encrypted-ado-feed-read-token

      - name: Prepare gradle.properties
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" --output ado-feed-read-token.txt ado-feed-read-token.txt.gpg
          cat ado-feed-read-token.txt | base64 -w 0
          
          $token=$(cat ado-feed-read-token.txt)
          
          echo -n $token | base64 -w 0

          # Define the directory and file path
          GRADLE_DIR="$HOME/.gradle"
          PROPERTIES_FILE="$GRADLE_DIR/gradle.properties"

          # Check if the .gradle directory exists, if not, create it
          if [ ! -d "$GRADLE_DIR" ]; then
            echo "$GRADLE_DIR not exists, create it."
            mkdir -p "$GRADLE_DIR"
          fi

          # Check if the gradle.properties file exists, if not, create it
          if [ ! -f "$PROPERTIES_FILE" ]; then
            touch "$PROPERTIES_FILE"
            echo "Created $PROPERTIES_FILE"
          else
            echo "$PROPERTIES_FILE already exists"
          fi

          cat $PROPERTIES_FILE

          echo "ado.artifacts.jiec-temp-org.mason-test-feed-in-personal-org.token=$token" >> cat $PROPERTIES_FILE

          cat cat $PROPERTIES_FILE

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Install dependencies
        run: pwd && ./gradlew build --info --stacktrace
